### ISSUE TITLE
Useful Code! Can I ask you some problem?

### ISSUE THREAD

**Issue by bkhotey4** [GanKunlu/Gesture-recognition-using-Myo-in-Tensorflow-#2]
I run in Anaconda3, there have some problems in "conv1D_ges_rec.py"
Traceback (most recent call last):
  File "conv1D_ges_rec.py", line 339, in <module>
    tf.app.run()
  File "C:\Users\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "conv1D_ges_rec.py", line 335, in main
    tf.gfile.MakeDirs(FLAGS.summaries_dir)
  File "C:\Users\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 442, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Users\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 458, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path), status)
  File "C:\Users\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: F:; No such file or directory
==============================================================
How can I solve this problem? Can you teach me? Please~

**Comment by GanKunlu** [comment]
Hi, you should create the directory summaries_dir before running the code. Set ""FLAGS.summaries_dir" to a real directory.
